name = "DocumenterDynamicDocStringTest"
uuid = "a7d46c60-f1b1-470d-abce-445475ab49c8"
authors = ["Michael Goerz <mail@michaelgoerz.net> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
